import time
from time import sleep
import pytest
from  playwright.sync_api import sync_playwright, Page, expect


@pytest.fixture(scope="module")
def browser():
    with sync_playwright() as p:
        browser = p.chromium.launch(headless=False)
        yield  browser
        browser.close()

@pytest.fixture
def page(browser):
    page = browser.new_page()
    yield page
    page.close()

def page_donations(page: Page):  # Функция для логина на сайт — принимает объект страницы
    page.goto("https://metanit.com/")
    page.click('//*[@id="header"]/div[2]/ul/li[2]/a')
    page.wait_for_url("https://metanit.com/donations.php", timeout=5000)
    time.sleep(1)
    page.goto("https://metanit.com/")
    expect(page).to_have_url("https://metanit.com/")
    time.sleep(1)

def page_VK(page: Page):
    page.goto("https://metanit.com/")
    page.click('//*[@id="header"]/div[2]/ul/li[3]/a')
    page.wait_for_url("https://vk.com/metanit", timeout=5000)
    time.sleep(3)
    page.fill('//*[@id="search-:r0:"]', 'Romanov')
    page.press('//*[@id="search-:r0:"]','Enter')
    time.sleep(3)
    page.goto("https://vk.com/metanit")
    time.sleep(1)
    page.goto("https://metanit.com/")
    expect(page).to_have_url("https://metanit.com/")
    time.sleep(1)

def page_android(page: Page):
    page.goto("https://metanit.com/")
    page.click('//*[@id="header"]/div[2]/ul/li[5]/a')
    page.wait_for_url("https://metanit.com/android.php", timeout=5000)
    time.sleep(1)
    page.click('//*[@id="container"]/div[1]/div[1]/div[1]/div[2]/ul[1]/li[1]/p/a')
    page.wait_for_url("https://www.rustore.ru/catalog/app/com.metanit.python_tutorial_full", timeout=5000)
    time.sleep(1)
    page.goto("https://metanit.com/android.php")
    time.sleep(1)
    page.click('//*[@id="container"]/div[1]/div[1]/div[1]/div[2]/ul[1]/li[2]/p/a')
    page.wait_for_url("https://www.rustore.ru/catalog/app/com.metanit.python_tutorial", timeout=5000)
    time.sleep(1)
    page.goto("https://metanit.com/android.php")
    time.sleep(1)
    page.click('//*[@id="container"]/div[1]/div[1]/div[1]/div[2]/ul[1]/li[3]/p/a')
    page.wait_for_url("https://play.google.com/store/apps/details?id=com.metanit.python_tutorial", timeout=5000)
    time.sleep(1)
    page.goto("https://metanit.com/android.php")
    time.sleep(1)
    page.goto("https://metanit.com/")
    time.sleep(2)

def page_display_fon(page: Page):
    page.goto("https://metanit.com/")
    page.click('//*[@id="toggle-theme"]')
    time.sleep(1)
    page.click('//*[@id="toggle-theme"]')
    time.sleep(1)

def page_find(page: Page):
    page.goto("https://metanit.com/")
    page.click('//*[@id="magnifying-glass"]')
    time.sleep(1)
    page.click('//*[@id="magnifying-glass"]')
    page.goto("https://metanit.com/")
    time.sleep(1)

def page_common(page: Page):
    page.goto("https://metanit.com/")
    page.click('//*[@id="menu"]/ul/li[1]/a')
    page.wait_for_url("https://metanit.com/common/", timeout=5000)
    time.sleep(1)
    page.click('//*[@id="container"]/div[1]/div[1]/div[1]/div[2]/div[2]/div/div/p[1]/a')
    time.sleep(1)
    page.goto('https://metanit.com/common/')
    time.sleep(1)
    page.click('//*[@id="container"]/div[1]/div[1]/div[1]/div[2]/div[2]/div/div/p[3]/a')
    time.sleep(1)
    page.goto("https://metanit.com/common/")
    time.sleep(1)
    page.goto("https://metanit.com/")
    page.click('//*[@id="menu"]/ul/li[2]/a')
    page.wait_for_url("https://metanit.com/assembler/", timeout=5000)
    time.sleep(1)
    page.click('//*[@id="container"]/div[1]/div[1]/div[1]/div[2]/div[1]/p[5]/a')
    time.sleep(1)
    page.goto("https://metanit.com/assembler/")
    time.sleep(1)
    page.click('//*[@id="container"]/div[1]/div[1]/div[1]/div[2]/div[1]/p[6]/a')
    time.sleep(1)
    page.goto("https://metanit.com/assembler/")
    time.sleep(1)
    page.click('//*[@id="container"]/div[1]/div[1]/div[1]/div[2]/div[1]/p[7]/a')
    time.sleep(1)
    page.goto("https://metanit.com/assembler/")
    time.sleep(1)
    page.click('//*[@id="container"]/div[1]/div[1]/div[1]/div[2]/div[1]/p[8]/a')
    time.sleep(1)
    page.goto("https://metanit.com/assembler/")
    page.goto("https://metanit.com/")
    time.sleep(1)

def page_sharp(page: Page):
    page.goto("https://metanit.com/")
    page.click('//*[@id="menu"]/ul/li[3]/a')
    page.wait_for_url("https://metanit.com/sharp/", timeout=5000)
    time.sleep(1)
    page.click('//*[@id="container"]/div[1]/div[1]/div[1]/div[2]/div[1]/p[2]/a')
    time.sleep(1)
    page.goto("https://metanit.com/sharp/")
    time.sleep(1)
    page.click('//*[@id="container"]/div[1]/div[1]/div[1]/div[2]/div[1]/p[3]/a')
    time.sleep(1)
    page.goto("https://metanit.com/sharp/")
    time.sleep(1)
    page.click('//*[@id="container"]/div[1]/div[1]/div[1]/div[2]/div[1]/p[4]/a')
    time.sleep(1)
    page.goto("https://metanit.com/sharp/")
    time.sleep(1)
    page.click('//*[@id="container"]/div[1]/div[1]/div[1]/div[2]/div[1]/p[5]/a')
    time.sleep(1)
    page.goto("https://metanit.com/sharp/")
    time.sleep(1)
    page.goto("https://metanit.com/")
    time.sleep(1)

def page_java(page: Page):
    page.goto("https://metanit.com/")
    page.click('//*[@id="menu"]/ul/li[4]/a')
    page.wait_for_url("https://metanit.com/java/", timeout=5000)
    time.sleep(1)
    page.click('//*[@id="container"]/div[1]/div[1]/div[1]/div[2]/div[1]/p[2]/a[1]')
    page.wait_for_url("https://metanit.com/java/tutorial/", timeout=5000)
    time.sleep(1)
    page.click('//*[@id="container"]/div[1]/div[1]/div[1]/ol/li[1]/p/a')
    page.wait_for_url("https://metanit.com/java/tutorial/1.1.php", timeout=5000)
    time.sleep(1)
    page.goto("https://metanit.com/java/tutorial/")
    time.sleep(1)
    page.click('//*[@id="container"]/div[1]/div[1]/div[1]/ol/li[1]/ol/li[1]/p/a')
    page.wait_for_url("https://metanit.com/java/tutorial/1.1.php", timeout=5000)
    time.sleep(1)
    page.goto("https://metanit.com/java/tutorial/")
    time.sleep(1)
    page.click('//*[@id="container"]/div[1]/div[1]/div[1]/ol/li[1]/ol/li[2]/p/a')
    page.wait_for_url("https://metanit.com/java/tutorial/1.6.php", timeout=5000)
    time.sleep(1)
    page.goto("https://metanit.com/java/tutorial/")
    time.sleep(1)
    page.click('//*[@id="container"]/div[1]/div[1]/div[1]/ol/li[1]/ol/li[3]/p/a')
    page.wait_for_url("https://metanit.com/java/tutorial/1.2.php", timeout=5000)
    time.sleep(1)
    page.goto("https://metanit.com/java/tutorial/")
    time.sleep(1)
    page.goto("https://metanit.com/java/")
    time.sleep(1)
    page.click('//*[@id="container"]/div[1]/div[1]/div[1]/div[2]/div[1]/p[2]/a[2]')
    page.wait_for_url("https://metanit.com/java/javafx/", timeout=5000)
    time.sleep(1)
    page.click('//*[@id="container"]/div[1]/div[1]/div[1]/ol/li[1]/p/a')
    page.wait_for_url("https://metanit.com/java/javafx/1.1.php", timeout=5000)
    time.sleep(1)
    page.goto("https://metanit.com/java/javafx/")
    time.sleep(1)
    page.click('//*[@id="container"]/div[1]/div[1]/div[1]/ol/li[1]/ol/li[1]/p/a')
    page.wait_for_url("https://metanit.com/java/javafx/1.1.php", timeout=5000)
    time.sleep(1)
    page.goto("https://metanit.com/java/javafx/")
    time.sleep(1)
    page.goto("https://metanit.com/java/")
    time.sleep(1)
    page.click('//*[@id="container"]/div[1]/div[1]/div[1]/div[2]/div[1]/p[3]/a')
    page.wait_for_url("https://metanit.com/java/android/", timeout=5000)
    time.sleep(1)
    page.click('//*[@id="container"]/div[1]/div[1]/div[1]/ol/li[1]/p/a')
    page.wait_for_url("https://metanit.com/java/android/1.1.php", timeout=5000)
    time.sleep(1)
    page.goto("https://metanit.com/java/android/")
    time.sleep(1)
    page.click('//*[@id="container"]/div[1]/div[1]/div[1]/ol/li[1]/ol/li[1]/p/a')
    page.wait_for_url("https://metanit.com/java/android/1.1.php", timeout=5000)
    time.sleep(1)
    page.goto("https://metanit.com/java/android/")
    time.sleep(1)
    page.click('//*[@id="container"]/div[1]/div[1]/div[1]/ol/li[1]/ol/li[2]/p/a')
    page.wait_for_url("https://metanit.com/java/android/1.2.php", timeout=5000)
    time.sleep(1)
    page.goto("https://metanit.com/java/android/")
    time.sleep(1)
    page.click('//*[@id="container"]/div[1]/div[1]/div[1]/ol/li[1]/ol/li[3]/p/a')
    page.wait_for_url("https://metanit.com/java/android/1.3.php", timeout=5000)
    time.sleep(1)
    page.goto("https://metanit.com/java/android/")
    time.sleep(1)
    page.goto("https://metanit.com/java/")
    time.sleep(1)
    page.click('//*[@id="container"]/div[1]/div[1]/div[1]/div[2]/div[1]/p[4]/a')
    page.wait_for_url("https://metanit.com/kotlin/tutorial/", timeout=5000)
    time.sleep(1)
    page.click('//*[@id="container"]/div[1]/div[1]/div[1]/ol/li[3]/p/a')
    page.wait_for_url("https://play.google.com/store/apps/details?id=com.metanit.kotlin_tutorial", timeout=5000)
    time.sleep(1)
    page.goto("https://metanit.com/kotlin/tutorial/")
    time.sleep(1)
    page.goto("https://metanit.com/java/")
    time.sleep(1)
    page.goto("https://metanit.com/")
    time.sleep(1)

def page_wb(page: Page):
    page.goto("https://metanit.com/")
    page.click('//*[@id="menu"]/ul/li[5]/a')
    page.wait_for_url("https://metanit.com/web/", timeout=5000)
    time.sleep(1)
    page.goto("https://metanit.com/")
    expect(page).to_have_url("https://metanit.com/")
    time.sleep(1)

def page_python(page: Page):
    page.goto("https://metanit.com/")
    page.click('//*[@id="menu"]/ul/li[6]/a')
    page.wait_for_url("https://metanit.com/python/", timeout=5000)
    time.sleep(1)
    page.click('//*[@id="container"]/div[1]/div[1]/div[1]/div[2]/div[1]/p[3]/a')
    page.wait_for_url("https://metanit.com/python/tutorial/", timeout=5000)
    time.sleep(1)
    page.click('//*[@id="container"]/div[1]/div[1]/div[1]/ol/li[3]/p/a')
    page.wait_for_url("https://play.google.com/store/apps/details?id=com.metanit.python_tutorial", timeout=5000)
    time.sleep(1)
    page.goto("https://metanit.com/python/tutorial/")
    time.sleep(1)
    page.goto("https://metanit.com/python/")
    time.sleep(1)
    page.click('//*[@id="container"]/div[1]/div[1]/div[1]/div[2]/div[1]/p[4]/a[1]')
    page.wait_for_url("https://metanit.com/python/django/", timeout=5000)
    time.sleep(1)
    page.goto("https://metanit.com/python/")
    time.sleep(1)
    page.click('//*[@id="container"]/div[1]/div[1]/div[1]/div[2]/div[1]/p[4]/a[2]')
    page.wait_for_url("https://metanit.com/python/fastapi/", timeout=5000)
    time.sleep(1)
    page.go_back(timeout=5000)
    time.sleep(1)
    page.click('//*[@id="container"]/div[1]/div[1]/div[1]/div[2]/div[1]/p[5]/a')
    page.wait_for_url("https://metanit.com/python/tkinter/")
    time.sleep(1)
    page.go_back(timeout=5000)
    time.sleep(1)
    page.click('//*[@id="container"]/div[1]/div[1]/div[1]/div[2]/div[1]/p[6]/a')
    page.wait_for_url("https://metanit.com/python/database/", timeout=5000)
    time.sleep(1)
    page.goto("https://metanit.com/python/")
    time.sleep(1)
    page.click('//*[@id="container"]/div[1]/div[1]/div[1]/div[2]/div[1]/p[7]/a')
    page.wait_for_url("https://metanit.com/python/network/", timeout=5000)
    time.sleep(1)
    page.goto("https://metanit.com/python/")
    time.sleep(1)
    page.click('//*[@id="container"]/div[1]/div[1]/div[1]/div[2]/div[1]/p[8]/a[1]')
    page.wait_for_url("https://metanit.com/python/recipes/", timeout=5000)
    time.sleep(1)
    page.go_back(timeout=5000)
    time.sleep(1)
    page.click('//*[@id="container"]/div[1]/div[1]/div[1]/div[2]/div[1]/p[8]/a[2]')
    page.wait_for_url("https://metanit.com/python/asm/", timeout=5000)
    time.sleep(1)
    page.goto("https://metanit.com/python/")
    time.sleep(1)
    page.goto("https://metanit.com/")
    time.sleep(1)

def page_c_2plus(page: Page):
    page.goto("https://metanit.com/")
    page.click('//*[@id="menu"]/ul/li[8]/a')
    page.wait_for_url("https://metanit.com/cpp/", timeout=5000)
    time.sleep(1)
    page.click('//*[@id="container"]/div[1]/div[1]/div[2]/div/a[1]')
    page.wait_for_url("https://metanit.com/cpp/tutorial/", timeout=5000)
    time.sleep(1)
    page.go_back(timeout=5000)
    time.sleep(1)
    page.click('//*[@id="container"]/div[1]/div[1]/div[2]/div/a[2]')
    page.wait_for_url("https://metanit.com/cpp/qt/", timeout=5000)
    time.sleep(1)
    page.go_back(timeout=5000)
    time.sleep(1)
    page.click('//*[@id="container"]/div[1]/div[1]/div[2]/div/a[3]')
    page.wait_for_url("https://metanit.com/cpp/vulkan/", timeout=5000)
    time.sleep(1)
    page.go_back(timeout=5000)
    time.sleep(1)
    page.goto("https://metanit.com/")
    time.sleep(1)

def page_SQL(page: Page):
    page.goto("https://metanit.com/")
    page.click('//*[@id="menu"]/ul/li[9]/a')
    page.wait_for_url("https://metanit.com/sql/", timeout=5000)
    time.sleep(1)
    page.click('//*[@id="container"]/div[1]/div[1]/div[2]/div/a[1]')
    page.wait_for_url("https://metanit.com/sql/sqlserver/", timeout=5000)
    time.sleep(1)
    page.go_back(timeout=5000)
    page.click('//*[@id="container"]/div[1]/div[1]/div[2]/div/a[2]')
    page.wait_for_url("https://metanit.com/sql/postgresql/", timeout=5000)
    time.sleep(1)
    page.go_back(timeout=5000)
    time.sleep(1)
    page.click('//*[@id="container"]/div[1]/div[1]/div[2]/div/a[3]')
    page.wait_for_url("https://metanit.com/sql/mysql/", timeout=5000)
    time.sleep(1)
    page.go_back(timeout=5000)
    time.sleep(1)
    page.click('//*[@id="container"]/div[1]/div[1]/div[2]/div/a[4]')
    page.wait_for_url("https://metanit.com/sql/sqlite/", timeout=5000)
    time.sleep(1)
    page.go_back(timeout=5000)
    time.sleep(1)
    page.goto("https://metanit.com/")
    time.sleep(1)

def page_Linux(page: Page):
    page.goto("https://metanit.com/")
    page.click('//*[@id="menu"]/ul/li[18]/a')
    page.wait_for_url("https://metanit.com/os/", timeout=5000)
    time.sleep(1)
    page.click('//*[@id="container"]/div[1]/div[1]/div[1]/div[2]/div[2]/div/div/p[1]/a')
    page.wait_for_url("https://metanit.com/os/linux/12.1.php", timeout=5000)
    time.sleep(1)
    page.click('//*[@id="browser"]/li[1]/span')
    time.sleep(1)
    page.click('//*[@id="browser"]/li[1]/ul/li[1]/span/a')
    page.wait_for_url("https://metanit.com/os/linux/1.1.php", timeout=5000)
    time.sleep(1)
    page.click('//*[@id="browser"]/li[1]/ul/li[2]/span/a')
    page.wait_for_url("https://metanit.com/os/linux/1.2.php", timeout=5000)
    page.goto("https://metanit.com/os/")
    time.sleep(1)
    page.click('//*[@id="container"]/div[1]/div[1]/div[1]/div[2]/div[2]/div/div/p[3]/a')
    page.wait_for_url("https://metanit.com/os/linux/", timeout=5000)
    time.sleep(1)
    page.click('//*[@id="container"]/div[1]/div[1]/div[1]/ol/li[1]/p/a')
    page.wait_for_url("https://metanit.com/os/linux/1.1.php", timeout=5000)
    time.sleep(1)
    page.go_back(timeout=5000)
    time.sleep(1)
    page.click('//*[@id="container"]/div[1]/div[1]/div[1]/ol/li[1]/ol/li[1]/p/a')
    page.wait_for_url("https://metanit.com/os/linux/1.1.php", timeout=5000)
    time.sleep(1)
    page.go_back(timeout=5000)
    time.sleep(1)
    page.click('//*[@id="container"]/div[1]/div[1]/div[1]/ol/li[1]/ol/li[2]/p/a')
    page.wait_for_url("https://metanit.com/os/linux/1.2.php", timeout=5000)
    time.sleep(1)
    page.goto("https://metanit.com/os/linux/")
    time.sleep(1)
    page.goto("https://metanit.com/os/")
    time.sleep(1)
    page.goto("https://metanit.com/")
    time.sleep(1)

def test_full_flow(page):
    #page_donations(page)
    #page_VK(page)
    #page_android(page)
    #page_display_fon(page)
    #page_find(page)
    #page_common(page)
    #page_sharp(page)
    #page_java(page)
    #page_wb(page)
    #page_python(page)
    #page_c_2plus(page)
    #page_SQL(page)
    page_Linux(page)


