from config.conftest import *

@pytest.fixture()
def com_page(page: Page):
    def page_common(page: Page):
        page.goto("https://metanit.com/")
        page.click('//*[@id="menu"]/ul/li[1]/a')
        page.wait_for_url("https://metanit.com/common/")
        page.wait_for_timeout(1000)
        page.click('//*[@id="container"]/div[1]/div[1]/div[1]/div[2]/div[2]/div/div/p[1]/a')
        page.wait_for_timeout(1000)
        page.goto('https://metanit.com/common/')
        page.wait_for_timeout(1000)
        page.click('//*[@id="container"]/div[1]/div[1]/div[1]/div[2]/div[2]/div/div/p[3]/a')
        page.wait_for_timeout(1000)
        page.goto("https://metanit.com/common/")
        page.wait_for_timeout(1000)
        page.goto("https://metanit.com/")
        page.click('//*[@id="menu"]/ul/li[2]/a')
        page.wait_for_url("https://metanit.com/assembler/")
        page.wait_for_timeout(1000)
        page.click('//*[@id="container"]/div[1]/div[1]/div[1]/div[2]/div[1]/p[5]/a')
        page.wait_for_timeout(1000)
        page.goto("https://metanit.com/assembler/")
        page.wait_for_timeout(1000)
        page.click('//*[@id="container"]/div[1]/div[1]/div[1]/div[2]/div[1]/p[6]/a')
        page.wait_for_timeout(1000)
        page.goto("https://metanit.com/assembler/")
        page.wait_for_timeout(1000)
        page.click('//*[@id="container"]/div[1]/div[1]/div[1]/div[2]/div[1]/p[7]/a')
        page.wait_for_timeout(1000)
        page.goto("https://metanit.com/assembler/")
        page.wait_for_timeout(1000)
        page.click('//*[@id="container"]/div[1]/div[1]/div[1]/div[2]/div[1]/p[8]/a')
        page.wait_for_timeout(1000)
        page.goto("https://metanit.com/assembler/")
        page.wait_for_timeout(1000)
        page.goto("https://metanit.com/")
        expect(page).to_have_url("https://metanit.com/")
        page.wait_for_timeout(1000)
    return page_common
