from config.conftest import *

@pytest.fixture()
def btn_linux(page: Page):
    def page_Linux():
        page.goto("https://metanit.com/")
        page.click('//*[@id="menu"]/ul/li[18]/a')
        page.wait_for_url("https://metanit.com/os/")
        time.sleep(1)
        page.click('//*[@id="container"]/div[1]/div[1]/div[1]/div[2]/div[2]/div/div/p[1]/a')
        page.wait_for_url("https://metanit.com/os/linux/12.1.php")
        time.sleep(1)
        page.click('//*[@id="browser"]/li[1]/span')
        time.sleep(1)
        page.click('//*[@id="browser"]/li[1]/ul/li[1]/span/a')
        page.wait_for_url("https://metanit.com/os/linux/1.1.php")
        time.sleep(1)
        page.click('//*[@id="browser"]/li[1]/ul/li[2]/span/a')
        page.wait_for_url("https://metanit.com/os/linux/1.2.php")
        page.goto("https://metanit.com/os/")
        time.sleep(1)
        page.click('//*[@id="container"]/div[1]/div[1]/div[1]/div[2]/div[2]/div/div/p[3]/a')
        page.wait_for_url("https://metanit.com/os/linux/")
        time.sleep(1)
        page.click('//*[@id="container"]/div[1]/div[1]/div[1]/ol/li[1]/p/a')
        page.wait_for_url("https://metanit.com/os/linux/1.1.php")
        time.sleep(1)
        page.go_back()
        time.sleep(1)
        page.click('//*[@id="container"]/div[1]/div[1]/div[1]/ol/li[1]/ol/li[1]/p/a')
        page.wait_for_url("https://metanit.com/os/linux/1.1.php")
        time.sleep(1)
        page.go_back()
        time.sleep(1)
        page.click('//*[@id="container"]/div[1]/div[1]/div[1]/ol/li[1]/ol/li[2]/p/a')
        page.wait_for_url("https://metanit.com/os/linux/1.2.php")
        time.sleep(1)
        page.goto("https://metanit.com/os/linux/")
        time.sleep(1)
        page.goto("https://metanit.com/os/")
        time.sleep(1)
        page.goto("https://metanit.com/")
        time.sleep(1)
        expect(page).to_have_url("https://metanit.com/")
    return page_Linux
